FROM node:18-alpine

WORKDIR /app

# Copy package files and config files
COPY package.json package-lock.json* ./
COPY postcss.config.js tailwind.config.js ./

# Install dependencies
RUN npm ci

# Copy application code
COPY . .

# Set environment variables
ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV production

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

# Build the application
RUN npm run build

# Use Next.js production server
CMD ["npm", "start"] 